# Generated by Django 5.1.2 on 2024-11-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='housemanager',
            name='house_type',
        ),
        migrations.RemoveField(
            model_name='housemanager',
            name='occupation',
        ),
        migrations.AddField(
            model_name='employer',
            name='house_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='number_people',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='number_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='type_contract',
            field=models.CharField(choices=[('Day', 'Day'), ('Weeks', 'Weeks'), ('Months', 'Months')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='housemanager',
            name='availability',
            field=models.CharField(choices=[('Immediately', 'Immediately'), ('Next-Week', 'Next-Week'), ('Next-Month', 'Next-Month')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='housemanager',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housemanager',
            name='type_contract',
            field=models.CharField(choices=[('Day', 'Day'), ('Weeks', 'Weeks'), ('Months', 'Months')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='housemanager',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
