# Generated by Django 5.1.2 on 2024-11-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_employer_age_remove_housemanager_house_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='type_contract',
        ),
        migrations.RemoveField(
            model_name='housemanager',
            name='type_contract',
        ),
        migrations.AddField(
            model_name='employer',
            name='number_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='preferred_contract_duration',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Weeks', 'Weeks'), ('Months', 'Months')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='user_type',
            field=models.CharField(choices=[('Employer', 'Employer'), ('HouseManager', 'HouseManager')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='housemanager',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housemanager',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='housemanager',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='housemanager',
            name='user_type',
            field=models.CharField(choices=[('Employer', 'Employer'), ('HouseManager', 'HouseManager')], max_length=20, null=True),
        ),
    ]
