# Generated by Django 4.2.13 on 2024-11-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_employer_type_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemanager',
            name='income',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='housemanager',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='housemanager',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
