# Generated by Django 5.1.2 on 2024-11-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_housemanager_income_housemanager_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemanager',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
