# Generated by Django 5.1.2 on 2024-11-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_housemanager_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemanager',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
