# Generated by Django 5.1.2 on 2024-11-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_employer_tribe_housemanager_tribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housemanager',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housemanager',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
